# lauv_fossen_params.yaml
lauv_dynamics:
  # 物理属性
  mass: 18.0
  volume: 0.017551374956865266
  fluid_density: 1028.0
  gravity: 9.81
  neutrally_buoyant: true
  
  # 重心(cog)和浮心(cob)
  cog: [0.0, 0.0, 0.0]
  cob: [0.0, 0.0, -0.01]
  
  # 刚体惯性张量 (Ixx, Iyy, Izz) 计算自: r=0.075, L=1.08, m=18
  inertia: [0.050625, 1.7749125, 1.7749125]
  
  # 附加质量矩阵 (Added Mass) 6x6
  # 行代表受力/力矩 (X, Y, Z, K, M, N)
  # 列代表加速度 (u_dot, v_dot, w_dot, p_dot, q_dot, r_dot)
  added_mass: [
  #   u_dot    v_dot    w_dot    p_dot    q_dot    r_dot
      1.0,     0.0,     0.0,     0.0,     0.0,     0.0,   # X (Surge) -> 各轴上加速度对X轴上运动附加质量的影响
      0.0,    16.0,     0.0,     0.0,     0.0,     0.0,   # Y (Sway)  -> 各轴上加速度对Y轴上运动附加质量的影响
      0.0,     0.0,    16.0,     0.0,     0.0,     0.0,   # Z (Heave) -> 各轴上加速度对Z轴上运动附加质量的影响
      0.0,     0.0,     0.0,     0.005,   0.0,     0.0,   # K (Roll)  -> 各轴上加速度对横滚运动时附加质量的影响
      0.0,     0.0,     0.0,     0.0,     1.3,     0.0,   # M (Pitch) -> 各轴上加速度对俯仰运动时附加质量的影响
      0.0,     0.0,     0.0,     0.0,     0.0,     1.3    # N (Yaw)   -> 各轴上加速度对偏航运动时附加质量的影响
  ]

  # 线性阻尼矩阵 (Linear Damping) 6x6
  # 行代表受力/力矩 (X, Y, Z, K, M, N)
  # 列代表速度 (u, v, w, p, q, r)
  linear_damping: [
  #   u        v        w        p        q        r
    -2.4,      0.0,     0.0,     0.0,     0.0,     0.0,   # X (Surge) -> 各轴上速度对X轴上运动产生的线性阻尼力系数
     0.0,    -23.0,     0.0,     0.0,     0.0,    11.5,   # Y (Sway)  -> 各轴上速度对Y轴上运动产生的线性阻尼力系数
     0.0,      0.0,   -23.0,     0.0,   -11.5,     0.0,   # Z (Heave) -> 各轴上速度对Z轴上运动产生的线性阻尼力系数
     0.0,      0.0,     0.0,    -0.3,     0.0,     0.0,   # K (Roll)  -> 各轴上速度对横滚运动产生的线性阻尼力系数
     0.0,      0.0,     3.1,     0.0,    -9.7,     0.0,   # M (Pitch) -> 各轴上速度对俯仰运动产生的线性阻尼力系数
     0.0,     -3.1,     0.0,     0.0,     0.0,    -9.7    # N (Yaw)   -> 各轴上速度对偏航运动产生的线性阻尼力系数
  ]

  # 二次阻尼矩阵 (Quadratic Damping) 6x6
  # 行代表受力/力矩 (X, Y, Z, K, M, N)
  # 列代表带绝对值的速度项 (|u|u, |v|v, |w|w, |p|p, |q|q, |r|r)
  quadratic_damping: [
  #  |u|u     |v|v     |w|w     |p|p     |q|q     |r|r
    -2.4,      0.0,     0.0,     0.0,     0.0,     0.0,   # X (Surge) -> 各轴上速度对X轴上运动产生的二次阻尼力系数（阻力与速度平行成正比）
     0.0,    -80.0,     0.0,     0.0,     0.0,     0.3,   # Y (Sway)  -> 各轴上速度对Y轴上运动产生的二次阻尼力系数（阻力与速度平行成正比）
     0.0,      0.0,   -80.0,     0.0,    -0.3,     0.0,   # Z (Heave) -> 各轴上速度对Z轴上运动产生的二次阻尼力系数（阻力与速度平行成正比）
     0.0,      0.0,     0.0, -0.0006,     0.0,     0.0,   # K (Roll)  -> 各轴上速度对横滚运动产生的二次阻尼力系数（阻力与速度平行成正比）
     0.0,      0.0,     1.5,     0.0,    -9.1,     0.0,   # M (Pitch) -> 各轴上速度对俯仰运动产生的二次阻尼力系数（阻力与速度平行成正比）
     0.0,     -1.5,     0.0,     0.0,     0.0,    -9.1    # N (Yaw)   -> 各轴上速度对偏航运动产生的二次阻尼力系数（阻力与速度平行成正比）
  ]


  # [新增机制] 前向速度耦合阻尼矩阵 (专门用来对抗 Munk 力矩)
  # 它会在代码里乘以 |u|，然后加到总阻尼中
  # linear_damping_forward_speed: [
  #    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
  #    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
  #    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
  #    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
  #    0.0,   0.0, -18.0,   0.0, -15.0,   0.0,  # M_w_u = -25.0, M_q_u = -15.0 (俯仰抗翻车)
  #    0.0,  18.0,   0.0,   0.0,   0.0, -15.0   # N_v_u =  25.0, N_r_u = -15.0 (偏航抗打转)
  # ]
  linear_damping_forward_speed: [
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # M_w_u = -25.0, M_q_u = -15.0 (俯仰抗翻车)
     0.0,   0.0,   0.0,   0.0,   0.0,   0.0   # N_v_u =  25.0, N_r_u = -15.0 (偏航抗打转)
  ]

