// Generated by gencpp from file uuv_control/State3D.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MESSAGE_STATE3D_H
#define UUV_CONTROL_MESSAGE_STATE3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uuv_control
{
template <class ContainerAllocator>
struct State3D_
{
  typedef State3D_<ContainerAllocator> Type;

  State3D_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , w(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)  {
    }
  State3D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , w(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _psi_type;
  _psi_type psi;

   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _w_type;
  _w_type w;

   typedef double _p_type;
  _p_type p;

   typedef double _q_type;
  _q_type q;

   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::uuv_control::State3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_control::State3D_<ContainerAllocator> const> ConstPtr;

}; // struct State3D_

typedef ::uuv_control::State3D_<std::allocator<void> > State3D;

typedef boost::shared_ptr< ::uuv_control::State3D > State3DPtr;
typedef boost::shared_ptr< ::uuv_control::State3D const> State3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_control::State3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_control::State3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_control::State3D_<ContainerAllocator1> & lhs, const ::uuv_control::State3D_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.phi == rhs.phi &&
    lhs.theta == rhs.theta &&
    lhs.psi == rhs.psi &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w &&
    lhs.p == rhs.p &&
    lhs.q == rhs.q &&
    lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_control::State3D_<ContainerAllocator1> & lhs, const ::uuv_control::State3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_control::State3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_control::State3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control::State3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control::State3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control::State3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control::State3D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_control::State3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d575c0223dfab5f094021a8013d98d0d";
  }

  static const char* value(const ::uuv_control::State3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd575c0223dfab5f0ULL;
  static const uint64_t static_value2 = 0x94021a8013d98d0dULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_control::State3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_control/State3D";
  }

  static const char* value(const ::uuv_control::State3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_control::State3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# === 位置 (NED 坐标系) ===\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"# === 姿态 (欧拉角) ===\n"
"float64 phi    # Roll (横滚)\n"
"float64 theta  # Pitch (俯仰)\n"
"float64 psi    # Yaw (偏航)\n"
"\n"
"# === 线速度 (机体坐标系) ===\n"
"float64 u      # Surge (纵荡)\n"
"float64 v      # Sway (横荡)\n"
"float64 w      # Heave (垂荡)\n"
"\n"
"# === 角速度 (机体坐标系) ===\n"
"float64 p      # Roll rate\n"
"float64 q      # Pitch rate\n"
"float64 r      # Yaw rate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::uuv_control::State3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_control::State3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.w);
      stream.next(m.p);
      stream.next(m.q);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_control::State3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_control::State3D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "q: ";
    Printer<double>::stream(s, indent + "  ", v.q);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_CONTROL_MESSAGE_STATE3D_H
