PidController:
  kp_u: 40.0
  ki_u: 20.0
  kd_u: 5.0
  max_output_u: 200.0
  max_integral_u: 50.0

  kp_pitch: 0.4
  ki_pitch: 0.0
  kd_pitch: 0.0
  max_output_pitch: 0.8
  max_integral_pitch: 0.0

  kp_q: 30.0
  ki_q: 3.0
  kd_q: 0.0
  max_output_q: 30.0
  max_integral_q: 10.0

  kp_yaw: 0.6
  ki_yaw: 0.0
  kd_yaw: 0.0
  max_output_yaw: 1.8
  max_integral_yaw: 0.0

  kp_r: 50.0
  ki_r: 15.0
  kd_r: 0.0
  max_output_r: 80.0
  max_integral_r: 15.0

# 请你仔细检查我的代码文件夹，现在有一个问题，当我将UUV从静止状态，设置航速为8m/s，俯仰角为30度，同时还设置指令偏航角90度时，UUV会“翻车”，且当我恢复0指令后，横滚角竟然一直是-3.14左右，另外，我发现有时候我输入指令后再恢复0指令，然后让UUV的期望航向角为2（当前为1），且俯仰角设置为某个和现在不同的数值，但是会出现UUV反向绕一圈再回到期望航向角2的情况，或者是UUV有时会“翻车”！！！请你仔细检查我的代码，是不是哪里有问题！？（我怀疑是偏航和俯仰控制中积分项的作用？导致PID的状态中残留了积分项？）